; This file was auto-generated by drush make
core = 7.x
api = 2

projects[drupal] = 7.x

projects[drupal_ci][type] = profile
projects[drupal_ci][download][type] = "git"
projects[drupal_ci][download][url] = "https://github.com/twers/drupal_ci.git"



