; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][version] = "1.2"

projects[devel][version] = "1.3"

projects[features][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[home_view_feature][download][type] = ""
projects[home_view_feature][download][url] = ""
projects[home_view_feature][type] = "module"
projects[home_view_feature][subdir] = "custom"
projects[home_view_feature][version] = "1.0"

projects[views][version] = "3.5"

projects[ckeditor][version] = ""

