; This file was auto-generated by drush make
core = 7.x
api = 2

projects[drupal] = 7.x

projects[cod][type] = profile
projects[cod][download][type] = "git"
projects[cod][download][url] = "https://github.com/twers/drupal_ci.git"
projects[cod][download][revision] = "7.x-1.x"



