; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][version] = "1.2"

projects[devel][version] = "1.3"

projects[features][version] = "1.0"

projects[views][version] = "3.5"

projects[ckeditor][version] = ""

projects[simpletest][version] = ""

projects[module_builder][version] = ""

projects[examples][version] = ""

projects[strongarm][version] = ""

projects[features_extra][version] = ""


